version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cryptodb
      - DB_SSL_MODE=disable
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cryptodb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schemes.sql:/docker-entrypoint-initdb.d/01-schemes.sql
      - ./db/trigger.sql:/docker-entrypoint-initdb.d/02-trigger.sql
    restart: unless-stopped

volumes:
  postgres_data:
